name: "Build and publish main branch"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build android module, run tests and pull apk to releases
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: bash ./gradlew build
      - name: Publish
        run: bash ./gradlew publish
        env:
          GITHUB_USER:  vlas-ilya
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.token }}