name: "Build and publish main branch"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build android module, run tests and pull apk to releases
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.2.6472646" --sdk_root=${ANDROID_SDK_ROOT}
      - name: cache gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: p
        run: git rev-parse --abbrev-ref HEAD
      - name: clean, build and publish
        run: ./gradlew clean test createDebugCoverageReport build publish
        env:
          GITHUB_USER: vlas-ilya
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.token }}
      - name: 'publish test report'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/testDebugUnitTest/*
      - name: 'publish test coverage report'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-coverage-report'
          path: build/reports/coverage/debug/*