name: "Build and publish main branch"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build android module, run tests and pull apk to releases
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: 'set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare NDK dir for caching ( workaround for https://github.com/actions/virtual-environments/issues/1337 )
        run: |
          sudo mkdir -p ${ANDROID_HOME}/ndk
          sudo chmod -R 777 ${ANDROID_HOME}/ndk
          sudo chown -R $USER:$USER ${ANDROID_HOME}/ndk

      - name: NDK Cache
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: ${ANDROID_HOME}/ndk
          key: ndk-cache-21.2.6472646-v2

      - name: Install NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.2.6472646"

      - name: 'cache gradle packages'
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: 'clean, build, test and publish'
        run: ./gradlew clean jacocoTestCoverageVerification build publish
        env:
          COVERAGE_LIMIT: 0.3
          GITHUB_USER: vlas-ilya
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.token }}

      - name: 'publish test report'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/testDebugUnitTest/*

      - name: 'publish test coverage report'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-coverage-report'
          path: build/reports/jacoco/generateJacocoTestReports/html/*
