name: "Build and publish main branch"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build android module, run tests and pull apk to releases
    runs-on: ubuntu-18.04
    container:
      image: docker://fabernovel/android:api-29-v1.1.0
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.0
      - name: gradle cache
        uses: actions/cache@v1.2.0
        with:
          path: /root/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: build and publish
        run: |
          ./gradlew clean assemble publish
        env:
          GITHUB_USER: vlas-ilya
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.token }}